### PR TITLE
Allows building different versions to ./build directory

### PR DESCRIPTION
**Pull request by shaqk**

### CODE REVIEW

**Comment by abourget** [comment]
Good thanks!

**Comment by maoueh** [comment]
Thanks for the contribution. What's your goal when using the `build.sh` script? 

The reason I'm asking is while this script is present, it's not what we use for releasing purposes. It was broken even before your PR because the command `go generate` was not correct (at least on OS X). Your new version is also partially broken because you don't call `go generate ./...` which is required since some required files for releasing purposes are generated by this command.

We use `goreleaser` for building purposes. Since this is what we use for release purposes, it will always be up-to-date with latest code base. I think we will remove the `build.sh` script altogether and only relies on the `goreleaser` tool to build stuff around.

I require an extra step, i.e. installing `goreleaser` tool, but it's more a release tool than a build tool, so I think it's ok.

So instead of `build.sh`, you could do `goreleaser --snapshot --skip-publish --rm-dist` which does all the heavy lifting that you added in your script. This could be added in the README for those you seek how to build the binaries for multiple platform without actually doing an official (local building).

For development, the recommended way to simply to do `go build -o dfuseeos ./cmd/dfuseeos`.

So, unless there is something I'm missing, I would close this PR and improve the README instead. Removal of `build.sh` is actually already happening in #8, which I think did not see this code change in this PR.

Would like your input before closing.

**Comment by shaqk** [comment]
Thanks for the feedback.

Goal of `build.sh` is to build, track and switch between binaries easily. Great for testing changes across deployments and have consistent version across builds

`build.sh` should be expanded to check, install and configure dfuse dependencies before building dfuse.

Why not keep `build.sh` and point users to use the `goreleaser tool` in the README if you prefer.

**Comment by maoueh** [comment]
My main concern right now in having a `build.sh` independent from our standard workflow is the maintenance cost. It means we have two places to maintain the same build logic.

If `goreleaser` was using `build.sh`, that would not be a problem, we would be required to maintain it correctly.

Is your intended usage of `build.sh` mainly for development purposes or to build for deployment purposes?

What about the `build.sh` doing simply `goreleaser --snapshot --skip-publish --rm-dist` and would print a nice error message with instructions if `goreleaser` binary is not found in path?

**Comment by shaqk** [comment]
Just read up on goreleaser, you are right,  it seems to do what I needed.
I can change build.sh to use goreleaser and then later add checks/installs for go/goreleaser

**Comment by maoueh** [comment]
@shaqk Ok good, but wait for the next release, we are going to update some instructions as build steps have changed a bit in this release, for example, so generated files like `eosq` static build are not included anymore out of the box and need to be built manually.

**Pull request closed without merging**
